swagger: '2.0'
info:
  title: Parsoid conversion API
  version: '2.0.0'
basePath: /v2
paths:
  /{domain}/html/{title}/{revision}:
    parameters:
      - name: domain
        in: path
        type: string
        required: true
        default: en.wikipedia.org
      - name: title
        in: path
        type: string
        required: true
        default: Main_Page
      - name: revision
        in: path
        type: string
        required: true
        default: 1
    get:
      produces:
        - application/json; profile=mediawiki.org/specs/data-parsoid/0.0.1
      responses:
        200:
          description: Page bundle
          schema:
            $ref: '#/definitions/PageBundle'
definitions:
  PageBundle:
    parameters:
      html:
        type: object
      data-parsoid:
        type: object